WITH AC_ACT AS (
SELECT * FROM(
    SELECT AC.*,
    ROW_NUMBER() OVER(PARTITION BY AC.REG_PES ORDER BY DATA_DANYCH DESC) AS NR_WYST
    FROM AC_RAPORT_MSR AC
    ) WHERE NR_WYST = 1
)
, DANE AS(
    SELECT ID_TR_DEF,
    CASE WHEN SUM(CZY_DEFAULT) > 0 THEN
        MIN(DATA_DANYCH) KEEP(DENSE_RANK LAST ORDER BY CZY_DEFAULT)
    ELSE NULL END AS DATA_DEFAULT90,
     CASE WHEN SUM(DEF_400) > 0 THEN
        MIN(DATA_DANYCH) KEEP(DENSE_RANK LAST ORDER BY DEF_400)
    ELSE NULL END AS DATA_DEFAULT400,
     CASE WHEN SUM(CZY_UTRATA_L) > 0 THEN
        MIN(DATA_DANYCH) KEEP(DENSE_RANK LAST ORDER BY CZY_UTRATA_L)
    ELSE NULL END AS DATA_UTRATY,
    MIN(DATA_DANYCH) AS DATA_MIN,
    MAX(DATA_DANYCH) AS DATA_MAX,
    MAX(KAPITAL_MSR_PLN) KEEP(DENSE_RANK LAST ORDER BY DATA_DANYCH) AS KAPITAL_MSR_AKT,
    MAX(CZY_UTRATA) KEEP(DENSE_RANK LAST ORDER BY DATA_DANYCH) AS CZY_UTRATA_AKT,
    MIN(CZY_DEFAULT) KEEP(DENSE_RANK LAST ORDER BY DATA_DANYCH) AS DEF_AKT
    FROM (
        SELECT AC.*,
        CASE WHEN AC.KREDYTZALEGLY_PLN > 400 AND AC.LICZA_DNI_OPOZN > 90 THEN 1 ELSE 0 END AS DEF_400,
        CASE WHEN AC.CZY_UTRATA = 'T' THEN 1 ELSE 0 END AS CZY_UTRATA_L
        FROM AC_RAPORT_MSR AC
    )
    GROUP BY ID_TR_DEF
)
SELECT RK.P_ID,
RK.P_REGON,
RK.P_NIP,
RK.CZY_SPOLKA_KOMUNALNA_SL,
RK.ZA_DATE,
RK.RODZAJ_KLIENTA_SKROCONA,
RK.K1_WARTOSC,
RK.KONIEC_KWARTALU,
RK.RAT_KLI_OST,
AC.ID_KLIENTA,
AC.ZADLUZENIE_PLN,
AC.KWOTA_WPL,
AC.NAZWA,
AC.ID_TR_DEF,
AC.CZY_DEFAULT,
AC.CZY_UTRATA,
CASE WHEN D.DATA_DEFAULT90 IS NOT NULL THEN
    D.DATA_DEFAULT90 - DATA_MIN 
    ELSE NULL END AS DNI_DO_DEF90
,CASE WHEN D.DATA_DEFAULT400 IS NOT NULL THEN
    D.DATA_DEFAULT400 - DATA_MIN 
    ELSE NULL END AS DNI_DO_DEF400
,CASE WHEN D.DATA_UTRATY IS NOT NULL THEN
    D.DATA_UTRATY - DATA_MIN 
    ELSE NULL END AS DNI_DO_UTRATY
,RK.K1_WARTOSC/100 ""KW/PAS""
,(1 - RK.K1_WARTOSC/100)/NULLIF(RK.K1_WARTOSC/100,0) AS ""DZWIGNIA""
FROM PS_DATA_RK_202303 RK
JOIN AC_RAPORT_MSR AC ON RK.P_REGON = AC.REG_PES AND RK.ZA_DATE = AC.DATA_DANYCH
JOIN DANE D ON AC.ID_TR_DEF = D.ID_TR_DEF
ORDER BY P_REGON,ZA_DATE
