WITH DANE AS(
    SELECT REG_PES,SUM(KAPITAL_MSR_PLN) AS SUMA_KAPITAL_MSR_PLN,SUM(KWOTA_WPL) AS SUM_KRED,SUM(ZADLUZENIE_PLN) AS SUM_ZADL,MAX(KOSZYK_MSSF) AS KOSZYK_MSSF, MAX(ID_KLIENTA) AS ID_KLIENTA
    FROM AC_RAPORT_MSR
    WHERE DATA_DANYCH = '28.02.2023'
    GROUP BY REG_PES
)
,DANEV2 AS (
SELECT B.*,
NVL((PRZYCHODY_RAZEM - LAST_PRZYCHODY_RAZEM)/NULLIF(LAST_PRZYCHODY_RAZEM,0),0)*100 ZMIANA_PRZYCHODY,
CASE WHEN LAST_DZWIGNIA >= 0 THEN DZWIGNIA - LAST_DZWIGNIA ELSE NULL END ZMIANA_DZWIGNIA,
ROS - LAST_ROS ZMIANA_ROS,
ROE - LAST_ROE ZMIANA_ROE
FROM (
    SELECT A.*, D.SUM_KRED,D.SUM_ZADL,D.SUMA_KAPITAL_MSR_PLN
    ,A.ZYSK_NETTO/NULLIF(A.KW,0) AS ROE
    ,D.KOSZYK_MSSF
    ,D.ID_KLIENTA
    ,(1 - K1/100)/NULLIF(K1/100,0) AS DZWIGNIA
    ,LAG(A.PRZYCHODY_RAZEM,1) OVER(PARTITION BY P_REGON ORDER BY D_TO_DATE) LAST_PRZYCHODY_RAZEM
    ,LAG(A.ZYSK_NETTO/NULLIF(A.KW,0)) OVER(PARTITION BY P_REGON ORDER BY D_TO_DATE) LAST_ROE
    ,LAG(A.ROS,1) OVER(PARTITION BY P_REGON ORDER BY D_TO_DATE) LAST_ROS
    ,LAG((1 - K1/100)/NULLIF(K1/100,0),1) OVER(PARTITION BY P_REGON ORDER BY D_TO_DATE) AS LAST_DZWIGNIA
    FROM PS_DATA_RK_DF_202303 A
    LEFT JOIN DANE D ON /*TO_DATE(A.D_TO_DATE,'DD.MM.YYYY') = D.DATA_DANYCH AND*/ A.P_REGON = D.REG_PES
) B --WHERE NR_WYSTAPIENIA = 1
)
,DANEV3 AS (
SELECT A.*
FROM (
    SELECT D.P_REGON,D.P_NIP
    ,D.ID_KLIENTA
    ,D.NAZWA_PODMIOTU,D.RATING_KONCOWY
    ,D.KOSZYK_MSSF,D.SUMA_KAPITAL_MSR_PLN
    ,D.D_TO_DATE,ZMIANA_PRZYCHODY,ZMIANA_DZWIGNIA,ZMIANA_ROS,ZMIANA_ROE
    ,CASE WHEN ZMIANA_PRZYCHODY <= -20 AND ZMIANA_DZWIGNIA > = 1 THEN 1 ELSE NULL END PRZESLANKA_DZIWGNIA
    ,CASE WHEN ZMIANA_ROS <= -3 AND ZMIANA_ROE <= -2 THEN 2 ELSE NULL END PRZESLANKA_PRZYCHODY
    FROM DANEV2 D
) A
)
select D.P_REGON,D.P_NIP
,D.ID_KLIENTA
,D.NAZWA_PODMIOTU,D.RATING_KONCOWY
,D.SUMA_KAPITAL_MSR_PLN
,PRZESLANKA_DZIWGNIA,PRZESLANKA_PRZYCHODY
,KOSZYK_MSSF
,ROUND(ZMIANA_PRZYCHODY,2) ZMIANA_PRZYCHODY, ROUND(ZMIANA_DZWIGNIA,2) ZMIANA_DZWIGNIA,ZMIANA_ROS,ROUND(ZMIANA_ROE,2) ZMIANA_ROE
FROM danev3 D WHERE d_to_date = '31.12.2022' --AND (PRZESLANKA_PRZYCHODY IS NOT NULL OR PRZESLANKA_DZIWGNIA IS NOT NULL) 
--AND KOSZYK_MSSF = 1



--SELECT D.*,A.P_REGON FROM DANE D 
--LEFT JOIN PS_DATA_RK_DF_202303 A ON D.REG_PES = A.P_REGON
--WHERE A.P_REGON IS NULL AND KOSZYK_MSSF = 1


--SELECT * FROM DANEV2 WHERE P_REGON = '302744758'


















