--WNIOSKI_CCPM_DETAL
--P_WNIOSKI_CCPM_NEW2
--WSM_WNIOSKI--V_RK_RAPORT_ODSTEPSTWA
--V_RAPORT_ODSTEPSTWA
--RAPORT_ODSTEPSTWA_DETAL
ALTER SESSION SET NLS_DATE_FORMAT='DD.MM.YYYY';
WITH DANE AS(
    SELECT ID_TR_DEF,
    CASE WHEN SUM(CZY_DEFAULT) > 0 THEN
        MIN(DATA_DANYCH) KEEP(DENSE_RANK LAST ORDER BY CZY_DEFAULT)
    ELSE NULL END AS DATA_DEFAULT90,
     CASE WHEN SUM(DEF_400) > 0 THEN
        MIN(DATA_DANYCH) KEEP(DENSE_RANK LAST ORDER BY DEF_400)
    ELSE NULL END AS DATA_DEFAULT400,
     CASE WHEN SUM(CZY_UTRATA_L) > 0 THEN
        MIN(DATA_DANYCH) KEEP(DENSE_RANK LAST ORDER BY CZY_UTRATA_L)
    ELSE NULL END AS DATA_UTRATY,
    MIN(DATA_DANYCH) AS DATA_MIN,
    MAX(DATA_DANYCH) AS DATA_MAX,
    MAX(KAPITAL_MSR_PLN) KEEP(DENSE_RANK LAST ORDER BY DATA_DANYCH) AS KAPITAL_MSR_AKT,
    MAX(CZY_UTRATA) KEEP(DENSE_RANK LAST ORDER BY DATA_DANYCH) AS CZY_UTRATA_AKT,
    MIN(CZY_DEFAULT) KEEP(DENSE_RANK LAST ORDER BY DATA_DANYCH) AS DEF_AKT
    FROM (
        SELECT AC.*,
        CASE WHEN AC.KREDYTZALEGLY_PLN > 400 AND AC.LICZA_DNI_OPOZN > 90 THEN 1 ELSE 0 END AS DEF_400,
        CASE WHEN AC.CZY_UTRATA = 'T' THEN 1 ELSE 0 END AS CZY_UTRATA_L
        FROM AC_RAPORT_MSR AC
    )
    GROUP BY ID_TR_DEF
)
,DANE_DETAL AS (
    SELECT O.*,
    CASE WHEN D.DATA_DEFAULT90 IS NOT NULL THEN
        D.DATA_DEFAULT90 - DATA_MIN 
        ELSE NULL END AS DNI_DO_DEF90
    ,CASE WHEN D.DATA_DEFAULT400 IS NOT NULL THEN
        D.DATA_DEFAULT400 - DATA_MIN 
        ELSE NULL END AS DNI_DO_DEF400
    ,CASE WHEN D.DATA_UTRATY IS NOT NULL THEN
    D.DATA_UTRATY - DATA_MIN 
    ELSE NULL END AS DNI_DO_UTRATY
    ,D.DATA_UTRATY
    ,D.DATA_DEFAULT90
    ,D.DATA_DEFAULT400
    ,CZY_UTRATA_AKT
    ,KAPITAL_MSR_AKT
    ,DATA_MIN PIERWSZE_WYSTAPIENIE_W_RAPORCIE
    ,D.DEF_AKT
    ,D.DATA_MAX AS DATA_OST_RAPORTU
    FROM RAPORT_ODSTEPSTWA_DETAL O
    JOIN DANE D ON O.ID_TR_DEF = D.ID_TR_DEF
)
,DANE_KORPO AS (
    SELECT O.*,
    CASE WHEN D.DATA_DEFAULT90 IS NOT NULL THEN
        D.DATA_DEFAULT90 - DATA_MIN 
        ELSE NULL END AS DNI_DO_DEF90
    ,CASE WHEN D.DATA_DEFAULT400 IS NOT NULL THEN
        D.DATA_DEFAULT400 - DATA_MIN 
        ELSE NULL END AS DNI_DO_DEF400
    ,CASE WHEN D.DATA_UTRATY IS NOT NULL THEN
        D.DATA_UTRATY - DATA_MIN 
        ELSE NULL END AS DNI_DO_UTRATY
    ,D.DATA_UTRATY
    ,D.DATA_DEFAULT90
    ,D.DATA_DEFAULT400
    ,CZY_UTRATA_AKT
    ,KAPITAL_MSR_AKT
    ,DEF_AKT
    ,DATA_MIN PIERWSZE_WYSTAPIENIE_W_RAPORCIE
    ,D.DATA_MAX AS DATA_OST_RAPORTU
    FROM V_RAPORT_ODSTEPSTWA O
    JOIN DANE D ON O.ID_TR_DEF = D.ID_TR_DEF
)

SELECT ((
SELECT (
SELECT COUNT(*) FROM DANE_DETAL 
WHERE PIERWSZE_WYSTAPIENIE_W_RAPORCIE BETWEEN '01.07.2021' AND '31.12.2021' AND ODSTEPSTWA_Z_RYZYKIEM > 0 --AND (DATA_DEFAULT400 <= '22/12/31')
) FROM DUAL A) / (
SELECT (
SELECT COUNT(A.ID_TR_DEF)--A.K1_PESEL,A.ID_TR_DEF,A.PRC_AUDIT_CD - AC.MIN_DATA,A.PRC_AUDIT_CD,AC.MIN_DATA 
FROM (
    SELECT * FROM(
        SELECT AA.*,
        ROW_NUMBER() OVER(PARTITION BY ID_TR_DEF ORDER BY AA.PRC_AUDIT_CD) NR_WYST
        FROM WNIOSKI_CCPM_DETAL AA
    ) WHERE NR_WYST = 1
) A
INNER JOIN (SELECT MIN(DATA_DANYCH) AS MIN_DATA,ID_TR_DEF FROM AC_RAPORT_MSR GROUP BY ID_TR_DEF) AC
ON A.ID_TR_DEF = AC.ID_TR_DEF
WHERE A.CZY_URUCH = 'T' AND A.PRC_AUDIT_CD - AC.MIN_DATA < 1 AND EXTRACT(YEAR FROM A.PRC_AUDIT_CD) = 2021 AND EXTRACT(MONTH FROM A.PRC_AUDIT_CD) BETWEEN 7 AND 12
--GROUP BY A.ID_TR_DEF
--ORDER BY ILE
) A FROM DUAL
)
) A FROM DUAL
